### ISSUE TITLE
npm WARN on Node 0.12.2

### ISSUE THREAD

**Issue by c0ntinuum** [jefflembeck/img-stats#3]
Hi Jeff,

Just wanted to let you know that `img-stats` is generating the following warning on Node 0.12.2.

```npm WARN engine img-stats@0.4.2: wanted: {"node":"~0.10"} (current: {"node":"0.12.2","npm":"2.8.4"})```

If you want a PR let me know and I'll work one out (should take 1 min).

Cheers!

Tod.

**Comment by jefflembeck** [comment]
Finally did some updating.

Done and done.

I assume you're seeing this in grunticon, in which case it'll get the update when it updates directory-encoder next (probably its next minor update)

**Comment by c0ntinuum** [comment]
So new to Node that I can't confirm your assumption...

I'd say your change `~0.10` to `>=0.10` will fix it ;)
